# Generated by Django 5.0.6 on 2024-06-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billing_created_at_billing_ispaid_billing_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='grand_total',
        ),
    ]
